# Mybatis Mate 配置
mybatis-mate:
  cert:
    grant: 请添加微信wx153666购买授权，不白嫖从我做起！
    license: GTAB70FMrYygsikYe+KxVabILYZ3McTOPYuEwV/mvx0Hp1dJPAwFzs4bUeTTWtbuXg0Ba96AnUHU7VUvkMtX4zraj3gw2ZoWhaIlLVLC/BwdyxPEtZdDufbEInzM8U+7i5BQlQZmHt8xCb5nceIUz3xm8sMZcnVPa1kMB1p/omF4pfEn46uo/Bc9L9QcWOEeqcXkGA1niuemnroueh7FgU8z8z5X+44GAaU9Dyr8TYcJlta8gUDWPYRcbtbayhVQ3e+PAaNJaqsDGSjjesOtybVbYFm7l6NjkdwRxhYYHyJ/WpentSou4uY3oc43XttESkcub/LYtUx60On04IFG/A==
  sharding:
    health: true # 健康检测
    primary: mysql # 默认选择数据源
    datasource:
      mysql:
        - key: t1
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
          username: root
          schema: test
        - key: t2
          cluster: slave # 从库读写分离时候负责 sql 查询操作，主库 master 默认可以不写
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/test2?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
          username: root
          schema: test2
      postgres:
        - key: t1
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://localhost:5432/test
          username: postgres
          password: 123456
          schema: test

# 允许bean定义重写
spring:
  main:
    allow-bean-definition-overriding: true

# Logger Config
logging:
  level:
    mybatis.mate: debug
    org.apache: debug
